class AddressValidationData(models.Model):
    countryCode = models.String()
    countryName = models.String()
    addressFormat = models.String()
    addressLatinFormat = models.String()
    allowedFields = models.String()
    requiredFields = models.String()
    upperFields = models.String()
    countryAreaType = models.String()
    countryAreaChoices = models.ChoiceValue()
    cityType = models.String()
    cityChoices = models.ChoiceValue()
    cityAreaType = models.String()
    cityAreaChoices = models.ChoiceValue()
    postalCodeType = models.String()
    postalCodeMatchers = models.String()
    postalCodeExamples = models.String()
    postalCodePrefix = models.String()

