class Agreement(models.Model):
    id = models.ID()
    publicationDate = models.Date()
    isPublished = models.Boolean()
    createdAt = models.DateTime()
    updatedAt = models.DateTime()
    content = models.String()
    contentHtml = models.String()
    tenant = models.Tenant()
    seoTitle = models.String()
    seoDescription = models.String()
    slug = models.String()
    title = models.String()
    commissionType = models.CommissionTypeEnum()
    defaultCommission = models.Decimal()
    markupCommissionType = models.MarkupCommissionTypeEnum()
    markupCommissionValue = models.Decimal()
    isActive = models.Boolean()
    granularCommissions = models.AgreementCommission()
    sellerAgreements = models.AgreementSellersCountableConnection()
    fees = models.AgreementFees()
    privateMetadata = models.MetadataItem()
    metadata = models.MetadataItem()

