class App(models.Model):
    id = models.ID()
    name = models.String()
    created = models.DateTime()
    isActive = models.Boolean()
    permissions = models.Permission()
    user = models.User()
    tokens = models.AppToken()
    privateMetadata = models.MetadataItem()
    metadata = models.MetadataItem()
    type = models.AppTypeEnum()
    webhooks = models.Webhook()
    aboutApp = models.String()
    dataPrivacy = models.String()
    dataPrivacyUrl = models.String()
    homepageUrl = models.String()
    supportUrl = models.String()
    configurationUrl = models.String()
    appUrl = models.String()
    version = models.String()
    accessToken = models.String()

