class Attribute(models.Model):
    id = models.ID()
    externalId = models.String()
    externalSource = models.String()
    productTypes = models.ProductTypeCountableConnection()
    productVariantTypes = models.ProductTypeCountableConnection()
    privateMetadata = models.MetadataItem()
    metadata = models.MetadataItem()
    inputType = models.AttributeInputTypeEnum()
    name = models.String()
    slug = models.String()
    allProductTypes = models.ProductType()
    values = models.AttributeValue()
    valueRequired = models.Boolean()
    visibleInStorefront = models.Boolean()
    filterableInStorefront = models.Boolean()
    filterableInDashboard = models.Boolean()
    availableInGrid = models.Boolean()
    storefrontSearchPosition = models.Int()
    createdBy = models.Seller()

