class AttributeValue(models.Model):
    id = models.ID()
    sortOrder = models.Int()
    tenant = models.Tenant()
    name = models.String()
    value = models.String()
    slug = models.String()
    attribute = models.Attribute()
    dateTime = models.DateTime()
    plainText = models.String()
    richText = models.String()
    currency = models.String()
    amount = models.Decimal()
    money = models.Money()
    reference = models.String()
    boolean = models.Boolean()
    file = models.File()
    fileUrl = models.String()
    date = models.Date()
    type = models.AttributeValueType()
    inputType = models.AttributeInputTypeEnum()

