class Collection(models.Model):
    id = models.ID()
    publicationDate = models.Date()
    privateMetadata = models.MetadataItem()
    metadata = models.MetadataItem()
    description = models.String()
    descriptionHtml = models.String()
    seoTitle = models.String()
    seoDescription = models.String()
    isVisible = models.Boolean()
    name = models.String()
    slug = models.String()
    products = models.ProductCountableConnection()
    variants = models.ProductVariantCountableConnection()
    backgroundImage = models.Image()
    isPublished = models.Boolean()
    type = models.CollectionTypeEnum()
    customFields = models.SelectedAttribute()
    sales = models.Sale()
    vouchers = models.Voucher()
    onSale = models.Boolean()

