class Fulfillment(models.Model):
    id = models.ID()
    fulfillmentOrder = models.Int()
    relatedTo = models.Fulfillment()
    order = models.Order()
    nauticalOrder = models.NauticalOrder()
    status = models.FulfillmentStatus()
    trackingCompany = models.String()
    trackingNumber = models.String()
    trackingUrl = models.String()
    shippingLabelUrl = models.String()
    created = models.DateTime()
    updated = models.DateTime()
    user = models.User()
    privateMetadata = models.MetadataItem()
    metadata = models.MetadataItem()
    lines = models.FulfillmentLine()
    seller = models.Seller()
    statusDisplay = models.String()
    warehouse = models.Warehouse()
    totalLinesQuantity = models.Int()
    totalLinesMoney = models.Money()
    customFields = models.SelectedAttribute()

