class NauticalOrderEvent(models.Model):
    id = models.ID()
    date = models.DateTime()
    type = models.OrderEventsEnum()
    user = models.User()
    message = models.String()
    email = models.String()
    emailType = models.OrderEventsEmailsEnum()
    amount = models.Float()
    paymentId = models.String()
    paymentGateway = models.String()
    quantity = models.Int()
    composedId = models.String()
    orderNumber = models.String()
    invoiceNumber = models.String()
    oversoldItems = models.String()
    lines = models.NauticalOrderEventOrderLineObject()
    warehouse = models.Warehouse()

