class OrderLine(models.Model):
    id = models.ID()
    privateMetadata = models.MetadataItem()
    metadata = models.MetadataItem()
    isLinePriceOverridden = models.Boolean()
    unitPriceOverriddenNote = models.String()
    note = models.String()
    productName = models.String()
    variantName = models.String()
    productSku = models.String()
    isShippingRequired = models.Boolean()
    quantityFulfilled = models.Int()
    quantityDeclined = models.Int()
    digitalContentUrl = models.DigitalContentUrl()
    order = models.Order()
    nauticalOrderLine = models.NauticalOrderLine()
    thumbnail = models.Image()
    unitPrice = models.TaxedMoney()
    totalPrice = models.TaxedMoney()
    variant = models.ProductVariant()
    translatedProductName = models.String()
    translatedVariantName = models.String()
    allocations = models.Allocation()
    priceBook = models.PriceBook()
    quantityOrdered = models.Int()
    unfulfilledQuantityRefunded = models.Int()
    fulfilledQuantityRefunded = models.Int()

