class Payment(models.Model):
    id = models.ID()
    gateway = models.String()
    isActive = models.Boolean()
    created = models.DateTime()
    modified = models.DateTime()
    token = models.String()
    checkout = models.Checkout()
    nauticalOrder = models.NauticalOrder()
    paymentMethodType = models.String()
    paymentMethodToken = models.String()
    customerIpAddress = models.String()
    privateMetadata = models.MetadataItem()
    metadata = models.MetadataItem()
    chargeStatus = models.PaymentChargeStatusEnum()
    actions = models.OrderAction()
    total = models.Money()
    capturedAmount = models.Money()
    transactions = models.Transaction()
    availableCaptureAmount = models.Money()
    availableRefundAmount = models.Money()
    creditCard = models.CreditCard()

