class Payout(models.Model):
    id = models.ID()
    privateMetadata = models.MetadataItem()
    metadata = models.MetadataItem()
    tenant = models.Tenant()
    created = models.String()
    updated = models.DateTime()
    startDate = models.Date()
    endDate = models.String()
    status = models.PayoutStatus()
    name = models.String()
    currency = models.String()
    vendorPayouts = models.VendorPayoutCountableConnection()
    vendors = models.Int()
    netSales = models.Money()
    discounts = models.Money()
    shipping = models.Money()
    commission = models.Money()
    fees = models.Money()
    refunds = models.Money()
    adjustments = models.Money()
    payout = models.Money()

