class Plugin(models.Model):
    id = models.ID()
    privateMetadata = models.JSONString()
    metadata = models.JSONString()
    company = models.String()
    category = models.PluginConfigurationCategory()
    descriptionShort = models.String()
    logoUrl = models.String()
    created = models.DateTime()
    externalUrl = models.String()
    supportUrl = models.String()
    allowSellers = models.Boolean()
    allowManyActivePluginsInCategory = models.Boolean()
    tenant = models.Tenant()
    identifier = models.String()
    name = models.String()
    description = models.String()
    active = models.Boolean()
    configuration = models.ConfigurationItem()
    defaultConfiguration = models.ConfigurationItem()
    supportSellerConfiguration = models.Boolean()
    version = models.String()

