class ProductType(models.Model):
    id = models.ID()
    externalId = models.String()
    externalSource = models.String()
    name = models.String()
    slug = models.String()
    isShippingRequired = models.Boolean()
    isDigital = models.Boolean()
    weight = models.Weight()
    isPriceOverrideAllowed = models.Boolean()
    createdBy = models.Seller()
    privateMetadata = models.MetadataItem()
    metadata = models.MetadataItem()
    products = models.ProductCountableConnection()
    taxType = models.TaxType()
    variantAttributes = models.Attribute()
    hasVariants = models.Boolean()
    productAttributes = models.Attribute()
    availableAttributes = models.AttributeCountableConnection()
    productFeatures = models.ProductTypeProductFeature()
    variantFeatures = models.ProductTypeVariantFeature()
    model = models.String()

